#!/bin/bash
# Скрипт для настройки GitHub Project через веб-интерфейс инструкции

echo "=== Настройка GitHub Project для RoverCtrl3 ==="
echo ""
echo "1. Откройте: https://github.com/users/Rhagtoo/projects"
echo "2. Нажмите 'New project'"
echo "3. Выберите 'Board' template"
echo "4. Название: 'RoverCtrl3 Development'"
echo "5. Описание: 'Project management for RoverCtrl3 development'"
echo ""
echo "6. Добавьте колонки:"
echo "   - Backlog"
echo "   - In Progress" 
echo "   - Review"
echo "   - Done"
echo ""
echo "7. Добавьте Issues в Backlog:"
echo "   - #3 OTA firmware update over WiFi"
echo "   - #4 Raspberry Pi 5 integration"
echo "   - #5 Joystick sensitivity settings"
echo "   - #6 Video and telemetry recording"
echo "   - #7 Autopilot with waypoint navigation"
echo ""
echo "8. Настройте автоматизацию (опционально):"
echo "   - При создании Issue → Backlog"
echo "   - При назначении assignee → In Progress"
echo "   - При создании PR → Review"
echo "   - При закрытии Issue → Done"
echo ""
echo "9. Добавьте метки (Labels):"
echo "   - bug, enhancement, documentation, question"
echo "   - priority: high, medium, low"
echo "   - android, firmware, hardware, ci/cd, ui"
echo ""
echo "10. Создайте Milestones:"
echo "    - v2.6 (Next Release)"
echo "    - v2.7"
echo "    - v2.8"
echo ""
echo "=== Альтернатива: Используйте GitHub CLI ==="
echo ""
echo "Установите GitHub CLI: https://cli.github.com/"
echo "Затем выполните:"
echo "gh auth login"
echo "gh project create --owner Rhagtoo --title 'RoverCtrl3 Development' --format board"
echo ""
echo "=== Ссылки ==="
echo "- Репозиторий: https://github.com/Rhagtoo/RoverCtrl3"
echo "- Issues: https://github.com/Rhagtoo/RoverCtrl3/issues"
echo "- Actions: https://github.com/Rhagtoo/RoverCtrl3/actions"
echo "- Projects: https://github.com/users/Rhagtoo/projects"